#!/usr/bin/env bash
# =============================================================================
# scaffold-ai CLI
#
# Single implementation for both entry points:
#   - devcontainer: the `scaffoldai` launcher (generated by install.sh) fetches
#     this exact file at the pinned feature version and runs it with --ref.
#   - standalone:   curl -fsSL https://raw.githubusercontent.com/.../cli.sh | bash
#
# Nothing about scaffold-ai is vendored anywhere: every run clones the
# scaffold-ai repo (scaffold.py + content/) at --ref (default: main), so
# there is no packaging step that can silently drop an asset.
#
# Subcommands:
#   install   Resolve config, install enabled binaries, run the scaffold.
#             Default when no subcommand is given (curl | bash unchanged).
#   sync      Fast path: skip binary installs, hash-check before re-scaffolding.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/FabrizioCafolla/scaffold-ai/main/cli.sh | bash
#   curl -fsSL https://raw.githubusercontent.com/FabrizioCafolla/scaffold-ai/main/cli.sh -o scaffold-ai.sh
#   bash scaffold-ai.sh [install|sync] [OPTIONS]
#
# Options:
#   --workspace DIR              Target workspace directory (default: current dir)
#   --tools claude|copilot|...   Comma-separated tools (default: claude; overridden by .scaffold-ai/config.yaml)
#   --no-mcp                     Skip .mcp.json creation
#   --no-hooks                   Skip hooks file management
#   --no-settings                Skip settings file creation
#   --no-gitignore               Skip .gitignore update
#   --no-defaults                Skip bundled default content (use only --content-repo)
#   --content-repo URL           GitHub repo URL with additional agents/skills
#   --content-repo-ref REF       Branch or tag of the content repo (default: main)
#   --ref BRANCH|TAG             scaffold-ai git ref to clone (default: main)
#   --local-path DIR             Use a local scaffold-ai checkout instead of cloning (dev/test, implies --force)
#   --no-rtk                     Skip RTK install and Claude PreToolUse hook
#   --no-headroom                Skip the Headroom CLI install
#   --wikictl                    Install wikictl (CLI + MCP server + skills; off by default)
#   --force                      Ignore the .scaffold-ai.lock hash and re-scaffold
#   --interactive                Guided prompt mode (mirrors devcontainer options)
#   -h, --help                   Show this help
#
# All of the above are the fallback tier: `.scaffold-ai/config.yaml` in the
# target workspace, when present, wins over any flag for the same setting.
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Defaults (fallback tier — .scaffold-ai/config.yaml overrides these)
# ---------------------------------------------------------------------------
SUBCOMMAND="install"
WORKSPACE="${PWD}"
TOOLS="claude"
CREATE_FILE_MCP="true"
CREATE_FILE_HOOKS="true"
CREATE_FILE_SETTING="true"
UPDATE_GITIGNORE="true"
INSTALL_DEFAULTS="true"
CONTENT_REPO=""
CONTENT_REPO_REF="main"
GIT_REF="main"
LOCAL_PATH=""
INSTALL_RTK="true"
INSTALL_HEADROOM="true"
INSTALL_WIKICTL="false"
FORCE="false"
INTERACTIVE="false"
readonly REPO_URL="https://github.com/FabrizioCafolla/scaffold-ai.git"
SCRIPT_NAME="$(basename "$0")"
readonly SCRIPT_NAME

TEMP_DIR=""
PYTHON="python3"
SCAFFOLD_SRC=""

# ---------------------------------------------------------------------------
# Cleanup
# ---------------------------------------------------------------------------
cleanup() {
    if [[ -n "${TEMP_DIR:-}" && -d "$TEMP_DIR" ]]; then
        rm -rf "$TEMP_DIR"
    fi
}
trap cleanup EXIT

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
die()  { echo "[ERROR] $*" >&2; exit 1; }
info() { echo "  $*"; }
warn() { echo "[WARN]  $*" >&2; }

usage() {
    cat <<EOF
scaffold-ai  scaffold AI agent/skill assets into any workspace

Usage: $SCRIPT_NAME [install|sync] [OPTIONS]
       curl -fsSL https://raw.githubusercontent.com/FabrizioCafolla/scaffold-ai/main/cli.sh | bash -s -- [install|sync] [OPTIONS]

Subcommands:
  install                 Install enabled binaries + run the scaffold (default)
  sync                    Fast path: skip binary installs, hash-check before re-scaffolding

Options:
  --workspace DIR         Target workspace directory (default: current dir)
  --tools LIST            Comma-separated tools: claude, copilot (default: claude)
  --no-mcp                Skip .mcp.json creation
  --no-hooks              Skip hooks file management
  --no-settings           Skip settings file creation
  --no-gitignore          Skip .gitignore update
  --no-defaults           Skip bundled default content
  --content-repo URL      GitHub repo URL with additional agents/skills
  --content-repo-ref REF  Branch or tag for content repo (default: main)
  --ref BRANCH|TAG        scaffold-ai git ref to clone (default: main)
  --local-path DIR        Use a local scaffold-ai checkout instead of cloning (dev/test, implies --force)
  --no-rtk                Skip RTK install and Claude hook
  --no-headroom           Skip the Headroom CLI install
  --wikictl               Install wikictl (file-based AI memory: CLI + MCP server + skills; off by default)
  --force                 Ignore the .scaffold-ai.lock hash and re-scaffold
  --interactive           Guided prompt mode
  -h, --help              Show this help

.scaffold-ai/config.yaml in the target workspace, when present, overrides
any of the above for the same setting.
EOF
    exit 0
}

# ---------------------------------------------------------------------------
# Interactive mode pure bash prompts, mirrors devcontainer option names
# ---------------------------------------------------------------------------
_prompt() {
    local question="$1" default="$2" varname="$3"
    local answer
    printf "  %s [%s]: " "${question}" "${default}"
    read -r answer
    answer="${answer:-${default}}"
    printf -v "${varname}" '%s' "${answer}"
}

_prompt_bool() {
    local question="$1" default="$2" varname="$3"
    local display answer
    display=$([ "${default}" = "true" ] && echo "Y/n" || echo "y/N")
    printf "  %s? [%s]: " "${question}" "${display}"
    read -r answer
    case "${answer,,}" in
        y|yes) printf -v "${varname}" '%s' "true" ;;
        n|no)  printf -v "${varname}" '%s' "false" ;;
        *)     printf -v "${varname}" '%s' "${default}" ;;
    esac
}

run_interactive() {
    echo ""
    echo "  scaffold-ai interactive setup"
    echo "  ─────────────────────────────────────────"
    _prompt       "tools (comma-separated: claude, copilot)" "${TOOLS}"          TOOLS
    _prompt_bool  "createFileMCP"                             "${CREATE_FILE_MCP}"      CREATE_FILE_MCP
    _prompt_bool  "createFileHooks"                           "${CREATE_FILE_HOOKS}"    CREATE_FILE_HOOKS
    _prompt_bool  "createFileSetting"                         "${CREATE_FILE_SETTING}"  CREATE_FILE_SETTING
    _prompt_bool  "updateGitignore"                           "${UPDATE_GITIGNORE}"     UPDATE_GITIGNORE
    _prompt_bool  "installDefaults"                           "${INSTALL_DEFAULTS}"     INSTALL_DEFAULTS
    _prompt_bool  "installRtk"                                "${INSTALL_RTK}"          INSTALL_RTK
    _prompt_bool  "installHeadroom"                           "${INSTALL_HEADROOM}"     INSTALL_HEADROOM
    _prompt_bool  "installWikictl"                            "${INSTALL_WIKICTL}"      INSTALL_WIKICTL
    _prompt       "contentRepo (GitHub URL, leave blank to skip)" "" CONTENT_REPO
    if [[ -n "${CONTENT_REPO}" ]]; then
        _prompt   "contentRepoRef" "${CONTENT_REPO_REF}" CONTENT_REPO_REF
    fi
    echo ""
}

# ---------------------------------------------------------------------------
# Content repo helpers
# ---------------------------------------------------------------------------
_get_remote_sha() {
    local url="$1" ref="$2"
    local auth_url="${url}"

    if [[ -n "${GITHUB_TOKEN:-}" ]]; then
        auth_url="https://x-access-token:${GITHUB_TOKEN}@${url#https://}"
    elif command -v gh &>/dev/null && gh auth token &>/dev/null 2>&1; then
        local token
        token=$(gh auth token)
        auth_url="https://x-access-token:${token}@${url#https://}"
    fi

    git ls-remote --exit-code "${auth_url}" "refs/heads/${ref}" 2>/dev/null | cut -f1 || echo ""
}

_clone_content_repo() {
    local url="$1" ref="$2" dest="$3"
    local auth_url="${url}"

    if [[ -n "${GITHUB_TOKEN:-}" ]]; then
        auth_url="https://x-access-token:${GITHUB_TOKEN}@${url#https://}"
    elif command -v gh &>/dev/null && gh auth token &>/dev/null 2>&1; then
        local token
        token=$(gh auth token)
        auth_url="https://x-access-token:${token}@${url#https://}"
    fi

    if ! git clone --quiet --depth 1 \
        --branch "${ref}" "${auth_url}" "${dest}" 2>/dev/null; then
        die "Failed to clone content repo: ${url} (ref: ${ref}). For private repos, set GITHUB_TOKEN."
    fi
    info "Content repo cloned (ref: ${ref})"
}

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
if [[ $# -gt 0 && "$1" != -* ]]; then
    case "$1" in
        install|sync) SUBCOMMAND="$1"; shift ;;
        *) die "Unknown subcommand: $1. Expected 'install' or 'sync'. Use -h for help." ;;
    esac
fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        --workspace)          WORKSPACE="$2";             shift 2 ;;
        --tools)              TOOLS="$2";                 shift 2 ;;
        --no-mcp)             CREATE_FILE_MCP="false";    shift ;;
        --no-hooks)           CREATE_FILE_HOOKS="false";  shift ;;
        --no-settings)        CREATE_FILE_SETTING="false"; shift ;;
        --no-gitignore)       UPDATE_GITIGNORE="false";   shift ;;
        --no-defaults)        INSTALL_DEFAULTS="false";   shift ;;
        --content-repo)       CONTENT_REPO="$2";          shift 2 ;;
        --content-repo-ref)   CONTENT_REPO_REF="$2";      shift 2 ;;
        --ref)                GIT_REF="$2";               shift 2 ;;
        --local-path)         LOCAL_PATH="$2";            shift 2 ;;
        --no-rtk)             INSTALL_RTK="false";        shift ;;
        --no-headroom)        INSTALL_HEADROOM="false";   shift ;;
        --wikictl)            INSTALL_WIKICTL="true";     shift ;;
        --force)              FORCE="true";               shift ;;
        --interactive)        INTERACTIVE="true";          shift ;;
        -h|--help)            usage ;;
        *) die "Unknown option: $1. Use -h for help." ;;
    esac
done

# ---------------------------------------------------------------------------
# Interactive mode (runs after flag parsing so flags set the defaults)
# ---------------------------------------------------------------------------
if [[ "${INTERACTIVE}" == "true" ]]; then
    run_interactive
fi

# ---------------------------------------------------------------------------
# Dependency checks
# ---------------------------------------------------------------------------
for cmd in git python3; do
    command -v "$cmd" &>/dev/null || die "'$cmd' is required but not found."
done

PY_MAJOR=$(python3 -c 'import sys; print(sys.version_info.major)')
PY_MINOR=$(python3 -c 'import sys; print(sys.version_info.minor)')
if [[ "$PY_MAJOR" -lt 3 ]] || [[ "$PY_MAJOR" -eq 3 && "$PY_MINOR" -lt 9 ]]; then
    PY_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
    die "Python 3.9+ required, found ${PY_VERSION}."
fi

# ---------------------------------------------------------------------------
# Setup: temp dir, pyyaml venv
# ---------------------------------------------------------------------------
TEMP_DIR="$(mktemp -d)"

_setup_python() {
    if ! python3 -c 'import yaml' 2>/dev/null; then
        info "Installing pyyaml in isolated venv..."
        python3 -m venv "${TEMP_DIR}/venv"
        "${TEMP_DIR}/venv/bin/pip" install --quiet pyyaml \
            || die "Failed to install pyyaml inside venv."
        PYTHON="${TEMP_DIR}/venv/bin/python3"
    fi
}

# ---------------------------------------------------------------------------
# Resolve scaffold-ai source: local checkout (dev/test) or fresh clone at --ref
# ---------------------------------------------------------------------------
_resolve_scaffold_ai_source() {
    SCAFFOLD_SRC="${TEMP_DIR}/scaffold-ai"
    if [[ -n "${LOCAL_PATH}" ]]; then
        [[ -f "${LOCAL_PATH}/scaffold.py" ]] \
            || die "--local-path '${LOCAL_PATH}' is not a scaffold-ai checkout (scaffold.py not found)."
        info "Using local scaffold-ai checkout: ${LOCAL_PATH}"
        cp -R "${LOCAL_PATH}" "${SCAFFOLD_SRC}"
    else
        info "Fetching scaffold-ai (ref: ${GIT_REF})..."
        git clone --quiet --depth 1 --branch "${GIT_REF}" "${REPO_URL}" "${SCAFFOLD_SRC}" \
            || die "Failed to fetch scaffold-ai at ref '${GIT_REF}' from ${REPO_URL}."
    fi
}

# ---------------------------------------------------------------------------
# .scaffold-ai/config.yaml: single source of truth, resolved on top of flags
# ---------------------------------------------------------------------------
_read_config() {
    local config_file="$1"
    "${PYTHON}" - "${config_file}" <<'PYEOF'
import shlex
import sys

import yaml

path = sys.argv[1]
with open(path) as f:
    cfg = yaml.safe_load(f) or {}


def emit(name, value):
    if value is None or value == "":
        return
    print(f"{name}={shlex.quote(str(value))}")


tools = cfg.get("tools")
if tools:
    emit("CFG_TOOLS", ",".join(tools))

install = cfg.get("install") or {}
for key, var in (
    ("rtk", "CFG_INSTALL_RTK"),
    ("headroom", "CFG_INSTALL_HEADROOM"),
    ("wikictl", "CFG_INSTALL_WIKICTL"),
):
    if key in install:
        emit(var, "true" if install[key] else "false")

scaffold = cfg.get("scaffold") or {}
for key, var in (
    ("createFileMCP", "CFG_CREATE_FILE_MCP"),
    ("createFileHooks", "CFG_CREATE_FILE_HOOKS"),
    ("createFileSetting", "CFG_CREATE_FILE_SETTING"),
    ("updateGitignore", "CFG_UPDATE_GITIGNORE"),
    ("installDefaults", "CFG_INSTALL_DEFAULTS"),
):
    if key in scaffold:
        emit(var, "true" if scaffold[key] else "false")

content_repo = cfg.get("contentRepo") or {}
if content_repo.get("url"):
    emit("CFG_CONTENT_REPO", content_repo["url"])
if content_repo.get("ref"):
    emit("CFG_CONTENT_REPO_REF", content_repo["ref"])
PYEOF
}

_load_config() {
    local config_file="${WORKSPACE}/.scaffold-ai/config.yaml"
    if [[ -f "${config_file}" ]]; then
        local resolved
        # Plain assignment (not `local var=$(...)`) so a parse failure's exit
        # status is actually visible here instead of being masked by `local`.
        resolved="$(_read_config "${config_file}")" \
            || die "Failed to parse ${config_file} — check it is valid YAML."
        eval "${resolved}"
    fi
    TOOLS="${CFG_TOOLS:-${TOOLS}}"
    INSTALL_RTK="${CFG_INSTALL_RTK:-${INSTALL_RTK}}"
    INSTALL_HEADROOM="${CFG_INSTALL_HEADROOM:-${INSTALL_HEADROOM}}"
    INSTALL_WIKICTL="${CFG_INSTALL_WIKICTL:-${INSTALL_WIKICTL}}"
    CREATE_FILE_MCP="${CFG_CREATE_FILE_MCP:-${CREATE_FILE_MCP}}"
    CREATE_FILE_HOOKS="${CFG_CREATE_FILE_HOOKS:-${CREATE_FILE_HOOKS}}"
    CREATE_FILE_SETTING="${CFG_CREATE_FILE_SETTING:-${CREATE_FILE_SETTING}}"
    UPDATE_GITIGNORE="${CFG_UPDATE_GITIGNORE:-${UPDATE_GITIGNORE}}"
    INSTALL_DEFAULTS="${CFG_INSTALL_DEFAULTS:-${INSTALL_DEFAULTS}}"
    CONTENT_REPO="${CFG_CONTENT_REPO:-${CONTENT_REPO}}"
    CONTENT_REPO_REF="${CFG_CONTENT_REPO_REF:-${CONTENT_REPO_REF}}"
}

# Copy-once starter config, seeded from the resolved (pre-YAML) fallback
# values — only runs when the workspace has no config.yaml yet.
_seed_starter_config() {
    local config_dir="${WORKSPACE}/.scaffold-ai"
    local config_file="${config_dir}/config.yaml"
    [[ -f "${config_file}" ]] && return 0

    local template="${SCAFFOLD_SRC}/config/config.default.yaml"
    if [[ ! -f "${template}" ]]; then
        warn "missing config/config.default.yaml template, skipping starter config"
        return 0
    fi

    mkdir -p "${config_dir}"
    "${PYTHON}" - "${template}" "${config_file}" \
        "${TOOLS}" "${INSTALL_RTK}" "${INSTALL_HEADROOM}" "${INSTALL_WIKICTL}" \
        "${CREATE_FILE_MCP}" "${CREATE_FILE_HOOKS}" "${CREATE_FILE_SETTING}" \
        "${UPDATE_GITIGNORE}" "${INSTALL_DEFAULTS}" "${CONTENT_REPO}" "${CONTENT_REPO_REF}" <<'PYEOF'
import sys

import yaml

(template_path, out_path, tools, i_rtk, i_hr, i_wc,
 mcp, hooks, settings, gi, defaults, cr_url, cr_ref) = sys.argv[1:14]


def b(v):
    return v.lower() == "true"


with open(template_path) as f:
    cfg = yaml.safe_load(f)

cfg["tools"] = [t for t in tools.split(",") if t]
cfg["install"]["rtk"] = b(i_rtk)
cfg["install"]["headroom"] = b(i_hr)
cfg["install"]["wikictl"] = b(i_wc)
cfg["scaffold"]["createFileMCP"] = b(mcp)
cfg["scaffold"]["createFileHooks"] = b(hooks)
cfg["scaffold"]["createFileSetting"] = b(settings)
cfg["scaffold"]["updateGitignore"] = b(gi)
cfg["scaffold"]["installDefaults"] = b(defaults)
cfg["contentRepo"]["url"] = cr_url
cfg["contentRepo"]["ref"] = cr_ref or "main"

with open(out_path, "w") as f:
    yaml.dump(cfg, f, default_flow_style=False, sort_keys=False)
PYEOF
    info "Created starter .scaffold-ai/config.yaml"
}

# ---------------------------------------------------------------------------
# RTK (optional) — install binary and register the Claude PreToolUse hook.
#
# Binary install (_install_rtk_binary) and hook merge (_merge_rtk_hook) are
# separate on purpose: every run fetches a *fresh* scaffold-ai clone (nothing
# is vendored), so the hook template in that clone always starts pristine —
# the merge must happen every time a scaffold pass runs, not just when the
# binary needs (re)installing. cmd_sync's full re-scaffold path calls
# _merge_rtk_hook too (via _run_scaffold); it never calls the binary install.
# ---------------------------------------------------------------------------
_install_rtk_binary() {
    if command -v rtk &>/dev/null; then
        info "RTK already installed: $(rtk --version 2>/dev/null || echo 'unknown version')"
        return 0
    fi

    info "Installing RTK..."
    case "$(uname -m)" in
        x86_64 | amd64) RTK_ARCH="x86_64" ;;
        aarch64 | arm64) RTK_ARCH="aarch64" ;;
        *) warn "RTK: unsupported arch $(uname -m), skipping"; return 0 ;;
    esac
    local rtk_bin_dir="/usr/local/bin"
    [[ -w "${rtk_bin_dir}" ]] || rtk_bin_dir="${HOME}/.local/bin"
    mkdir -p "${rtk_bin_dir}"
    if curl -fsSL \
        "https://github.com/rtk-ai/rtk/releases/latest/download/rtk-${RTK_ARCH}-unknown-linux-gnu.tar.gz" \
        | tar xz -C "${rtk_bin_dir}" rtk; then
        chmod 755 "${rtk_bin_dir}/rtk"
        info "RTK installed to ${rtk_bin_dir}/rtk"
    else
        warn "RTK install failed, continuing without it"
    fi
}

_merge_rtk_hook() {
    local hooks_file="${SCAFFOLD_SRC}/config/claude/hooks.json"
    [[ -f "${hooks_file}" ]] || return 0

    RTK_HOOKS_FILE="${hooks_file}" "${PYTHON}" - <<'PYEOF'
import json, os

path = os.environ["RTK_HOOKS_FILE"]
with open(path) as f:
    hooks = json.load(f)

entry = {
    "matcher": "Bash",
    "hooks": [{"type": "command", "command": "rtk hook claude"}],
}
pre = hooks.setdefault("PreToolUse", [])
if not any(
    h.get("command") == "rtk hook claude"
    for item in pre
    for h in item.get("hooks", [])
):
    pre.append(entry)
    with open(path, "w") as f:
        json.dump(hooks, f, indent=2)
        f.write("\n")
    print("  RTK PreToolUse hook added to Claude hooks template")
PYEOF
}

# ---------------------------------------------------------------------------
# Headroom (installed by default) — request-level context compression CLI
#
# Not a hook and not auto-active: activate per-session with `headroom wrap
# claude`. RTK stays the active input-side layer; Headroom only stacks on
# top when explicitly wrapped.
# ---------------------------------------------------------------------------
_install_headroom() {
    if command -v headroom &>/dev/null; then
        info "Headroom already installed: $(headroom --version 2>/dev/null || echo 'unknown version') (inactive until 'headroom wrap claude')"
    elif command -v uv &>/dev/null; then
        info "Installing Headroom CLI..."
        if uv tool install "headroom-ai[proxy]"; then
            info "Headroom installed: $(headroom --version 2>/dev/null || echo 'unknown version') (inactive until 'headroom wrap claude')"
        else
            warn "Headroom install failed, continuing without it"
        fi
    else
        warn "Headroom requires uv (not found), skipping"
    fi
}

# ---------------------------------------------------------------------------
# wikictl (optional) — file-based AI memory layer (CLI + MCP server). Installed
# from the fetched scaffold-ai checkout, mirroring Headroom. The MCP entry and
# skills are wired by scaffold.py below.
# ---------------------------------------------------------------------------
_install_wikictl() {
    if command -v wikictl &>/dev/null; then
        info "wikictl already installed: $(wikictl --version 2>/dev/null || echo 'unknown version')"
    elif command -v uv &>/dev/null; then
        info "Installing wikictl..."
        if uv tool install "${SCAFFOLD_SRC}/wikictl[serve]"; then
            info "wikictl installed: $(wikictl --version 2>/dev/null || echo 'unknown version')"
        else
            warn "wikictl install failed, continuing without it"
        fi
    else
        warn "wikictl requires uv (not found), skipping"
    fi
}

# ---------------------------------------------------------------------------
# Run scaffold.py with the fully resolved config
# ---------------------------------------------------------------------------
_run_scaffold() {
    # Re-merge the RTK hook into this run's freshly cloned hooks.json — the
    # clone is always pristine, and scaffold.py replaces the hooks key wholesale.
    if [[ "${INSTALL_RTK}" == "true" && "${CREATE_FILE_HOOKS}" == "true" ]]; then
        _merge_rtk_hook
    fi

    local extra_args=()
    [[ -n "${CONTENT_REPO_LOCAL_PATH:-}" ]] && extra_args+=(--content-repo-local-path "${CONTENT_REPO_LOCAL_PATH}")
    [[ -n "${CONTENT_REPO_SHA:-}" ]] && extra_args+=(--content-repo-sha "${CONTENT_REPO_SHA}")

    "${PYTHON}" "${SCAFFOLD_SRC}/scaffold.py" \
        --workspace               "${WORKSPACE}" \
        --tools                   "${TOOLS}" \
        --create-file-mcp         "${CREATE_FILE_MCP}" \
        --create-file-hooks       "${CREATE_FILE_HOOKS}" \
        --create-file-setting     "${CREATE_FILE_SETTING}" \
        --update-gitignore        "${UPDATE_GITIGNORE}" \
        --install-defaults        "${INSTALL_DEFAULTS}" \
        --install-wikictl         "${INSTALL_WIKICTL}" \
        "${extra_args[@]+"${extra_args[@]}"}"
}

# ---------------------------------------------------------------------------
# install: resolve config → install enabled binaries → clone content repo → scaffold
# ---------------------------------------------------------------------------
cmd_install() {
    _resolve_scaffold_ai_source
    _setup_python
    _load_config
    _seed_starter_config

    [[ "${INSTALL_RTK}" == "true" ]] && _install_rtk_binary
    [[ "${INSTALL_HEADROOM}" == "true" ]] && _install_headroom
    [[ "${INSTALL_WIKICTL}" == "true" ]] && _install_wikictl

    CONTENT_REPO_LOCAL_PATH=""
    if [[ -n "${CONTENT_REPO}" ]]; then
        info "Cloning content repo (ref: ${CONTENT_REPO_REF})..."
        _clone_content_repo "${CONTENT_REPO}" "${CONTENT_REPO_REF}" "${TEMP_DIR}/content-repo"
        CONTENT_REPO_LOCAL_PATH="${TEMP_DIR}/content-repo"
    fi

    # The lock hash is identity-based (scaffold-ai HEAD SHA + content repo SHA),
    # so uncommitted local changes never alter it: a local checkout always forces.
    if [[ "${FORCE}" == "true" || -n "${LOCAL_PATH}" ]]; then
        if [[ -f "${WORKSPACE}/.scaffold-ai.lock" ]]; then
            info "Forcing re-scaffold (removing .scaffold-ai.lock)"
            rm -f "${WORKSPACE}/.scaffold-ai.lock"
        fi
    fi

    echo ""
    _run_scaffold
}

# ---------------------------------------------------------------------------
# sync: skip binary installs; hash-check via ls-remote before re-scaffolding
# ---------------------------------------------------------------------------
cmd_sync() {
    _resolve_scaffold_ai_source
    _setup_python
    _load_config

    CONTENT_REPO_SHA=""
    if [[ -n "${CONTENT_REPO}" ]]; then
        CONTENT_REPO_SHA=$(_get_remote_sha "${CONTENT_REPO}" "${CONTENT_REPO_REF}")
    fi

    # Fast check: skip if content repo is defined but SHA is unavailable (auth failed).
    # Without the SHA the hash is incomplete — a false match would silently skip private content.
    if [[ -z "${CONTENT_REPO}" || -n "${CONTENT_REPO_SHA}" ]]; then
        if "${PYTHON}" "${SCAFFOLD_SRC}/scaffold.py" \
            --workspace "${WORKSPACE}" \
            --check-only \
            ${CONTENT_REPO_SHA:+--content-repo-sha "${CONTENT_REPO_SHA}"}; then
            exit 0
        fi
    fi

    CONTENT_REPO_LOCAL_PATH=""
    if [[ -n "${CONTENT_REPO}" ]]; then
        info "Cloning content repo (ref: ${CONTENT_REPO_REF})..."
        _clone_content_repo "${CONTENT_REPO}" "${CONTENT_REPO_REF}" "${TEMP_DIR}/content-repo"
        CONTENT_REPO_LOCAL_PATH="${TEMP_DIR}/content-repo"
    fi

    echo ""
    _run_scaffold
}

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------
case "${SUBCOMMAND}" in
    install) cmd_install ;;
    sync)    cmd_sync ;;
esac
