copilot:
  base_dir: .github
  agents:
    dir: agents
    suffix: .agent.md
  skills:
    dir: skills
    filename: SKILL.md
  prompts:
    dir: prompts
    suffix: .prompt.md
  extra_files:
    mcp:
      - source: config/extra/copilot/mcp-config.json
        dest: .copilot/mcp-config.json
        ignore: false

claude:
  base_dir: .claude
  agents:
    dir: agents
    suffix: .md
  skills:
    dir: skills
    filename: SKILL.md
  prompts:
    dir: commands
    suffix: .md
  extra_files:
    mcp:
      - source: config/extra/claude/mcp.json
        dest: .mcp.json
    settings:
      - source: config/extra/claude/settings.json
        dest: .claude/settings.json
        ignore: false
      - source: config/extra/claude/settings.local.json
        dest: .claude/settings.local.json
        ignore: true
